---
- name: Create Linux VMs
  azure_rm_virtualmachine:
    resource_group: "{{ resource_group }}"
    name: "{{ item.name }}"
    vm_size: Standard_B1ls
    admin_username: azureuser
    ssh_password_enabled: no
    ssh_public_keys:
      - path: /home/azureuser/.ssh/authorized_keys
        key_data: "{{ ssh_key }}"
    network_interfaces: "{{ item.nic }}"
    os_type: Linux
    image:
      offer: UbuntuServer
      publisher: Canonical
      sku: 18.04-LTS
      version: latest
  async: 300
  poll: 5
  loop:
    - {name: vm-linux-bastation, nic: nic-internal3}
    - {name: vm-linux-dns, nic: nic-external}