---
- name: Config the linux command and control server
  hosts: linux
  become: true
  become_user: root

  tasks:
    - name: Update and upgrade apt packages
      apt:
        upgrade: yes
        update_cache: yes
    
    - name: Install python3.8 & pip
      apt:
        pkg:
          - python3.8
          - python3-pip
        state: present

    - name: Create directory
      file:
        path: /root/dns-server
        state: directory

    - name: Download required files from Github
      get_url:
        url: "https://raw.githubusercontent.com/mart123p/dns-tunnel-example/master/server/{{ item }}"
        dest: "/root/dns-server/{{ item }}"
      loop:
        - server.py
        - requirements.txt

    - name: Download rat code from Github
      get_url:
        url: "https://raw.githubusercontent.com/mart123p/dns-tunnel-example/master/rat/rat.go"
        dest: "/root/dns-server/rat.go"
    
    - name: Install requierements
      shell:
        chdir: /root/dns-server/ 
        cmd: pip3 install -r requirements.txt