---
- name: Config the host to its requiered state
  hosts: win_host

  vars:
    domain_name: example.com

  tasks:
    - name: Join EXAMPLE domain
      win_domain_membership:
        dns_domain_name: "{{ domain_name }}"
        domain_admin_user: "EXAMPLE\\Administrator"
        domain_admin_password: "{{ lookup('file', 'creds/dc_administrator') }}"
      register: ad
      
    - name: Reboot after join
      win_reboot:
        msg: "Joining AD. Rebooting..."
        pre_reboot_delay: 15
      when: ad.changed

    - name: Copy RAT files
      win_copy:
        src: files/rat.exe
        dest: "C:\\Demo\\rat.exe"
      
    - name: Copy secret file
      win_copy:
        src: files/secret.txt
        dest: "C:\\confidential\\acquisition.txt"