---
- name: Config the host to its requiered state
  hosts: win_host

  vars:
    domain_name: example.com

  tasks:
    - name: Make sure to use the DNS server from AD
      win_dns_client:
        adapter_names: Ethernet
        ipv4_addresses: 10.0.0.4
      
    - name: Join EXAMPLE domain
      win_domain_membership:
        dns_domain_name: "{{ domain_name }}"
        domain_admin_user: "EXAMPLE\\azureuser"
        domain_admin_password: "{{ lookup('file', 'creds/vm-win-dc') }}"
        state: domain
      register: ad
      
    - name: Reboot after join
      win_reboot:
        msg: "Joining AD. Rebooting..."
        pre_reboot_delay: 15
      when: ad.changed

    - name: Create directories
      win_file:
        path: "{{ item }}"
        state: directory
      loop:
        - "C:\\demo"
        - "C:\\demo\\downloads"
        - "C:\\confidential"

    - name: Copy RAT files
      win_copy:
        src: files/rat.exe
        dest: "C:\\demo\\rat.exe"
      
    - name: Copy secret file
      win_copy:
        src: files/secret.txt
        dest: "C:\\confidential\\acquisition.txt"

    - name: Setting RDP permissions for User1
      win_group_membership:
        name: "Remote Desktop Users"
        state: present
        members:
          - "EXAMPLE\\User1"

    - name: Install various programs
      win_chocolatey:
        name:
          - wireshark
          - firefox
          - notepadplusplus
        state: present

    - name: Download NpCap must be installed manually because of the licence
      win_get_url:
        url: https://nmap.org/npcap/dist/npcap-1.00.exe
        dest: "C:\\demo\\downloads\\npcap-1.00.exe"
      