all:
  vars:
    ansible_host: 127.0.0.1
    ansible_user: azureuser

win_dc:
  hosts:
    win1:
      ansible_password: "{{ lookup('password', 'creds/vm-win-dc length=20') }}"
      ansible_port: 6001
      ansible_connection: winrm
      ansible_winrm_server_cert_validation: ignore

win_host:
  hosts:
    win2:
      ansible_password: "{{ lookup('password', 'creds/vm-win-host1 length=20') }}"
      ansible_port: 6002
      ansible_connection: winrm
      ansible_winrm_server_cert_validation: ignore

linux:
  hosts:
    rogue:
      ansible_port: 6050
      ansible_ssh_private_key_file: creds/ssh/id_rsa
      ansible_python_interpreter: /usr/bin/python3
      ansible_becore: yes
      ansible_become_method: sudo