---
- name: Create VMs Windows
  azure_rm_virtualmachine:
    resource_group: "{{ resource_group }}"
    name: "{{ item.name }}"
    vm_size: "{{ item.size }}"
    admin_username: azureuser
    admin_password: "{{ lookup('password', 'creds/' + item.name +' length=20') }}"
    network_interfaces: "{{ item.nic }}"
    os_type: Windows
    image:
      offer: WindowsServer
      publisher: MicrosoftWindowsServer
      sku: 2019-Datacenter
      version: latest
  async: 300
  poll: 0
  register: windows_deploy
  loop:
    - {name: vm-win-dc, nic: nic-internal1, size: Standard_B1ms}
    - {name: vm-win-host1, nic: nic-internal2, size: Standard_B1ms}

- name: Check Windows VM creation status
  async_status:
    jid: "{{ item.ansible_job_id }}"
  register: job_result
  until: job_result.finished
  retries: 300
  delay: 10
  loop: "{{ windows_deploy.results }}"

- name: Enable WinRM for Ansible on Windows Machines
  azure_rm_virtualmachineextension:
    name: winrm-extension
    resource_group: "{{ resource_group }}"
    virtual_machine_name: "{{ item.name }}"
    publisher: Microsoft.Compute
    virtual_machine_extension_type: CustomScriptExtension
    type_handler_version: '1.9'
    settings: '{"fileUris": ["https://raw.githubusercontent.com/ansible/ansible/devel/examples/scripts/ConfigureRemotingForAnsible.ps1"],"commandToExecute": "powershell -ExecutionPolicy Unrestricted -File ConfigureRemotingForAnsible.ps1"}'
    auto_upgrade_minor_version: true
  async: 300
  poll: 0
  register: windows_ansible
  loop:
    - {name: vm-win-dc}
    - {name: vm-win-host1}

# Wait for other long running tasks
- name: Check Linux VM creation status
  async_status:
    jid: "{{ item.ansible_job_id }}"
  register: job_result
  until: job_result.finished
  retries: 300
  delay: 10
  loop: "{{ linux_deploy.results }}"

- name: Check Windows VM preperation status
  async_status:
    jid: "{{ item.ansible_job_id }}"
  register: job_result
  until: job_result.finished
  retries: 300
  delay: 10
  loop: "{{ windows_ansible.results }}"
